### ISSUE TITLE
Отсутствующие иконки с версии 0.8.9

### ISSUE THREAD

**Issue by iTeeLion** [et-nik/gameap-legacy#12]
Начиная с версии 0.8.9 в сборках отсутствуют иконки:
/themes/default/ubeast/images/icons/remote_folder.png
![remote_folder](https://cloud.githubusercontent.com/assets/13005248/8289878/cc2cac2e-1927-11e5-9805-1bd1069c9ec3.png)
/themes/system/images/bullet_grey.png
![bullet_grey](https://cloud.githubusercontent.com/assets/13005248/8289879/cc32aaac-1927-11e5-9076-6b8081032a30.png)

**Comment by et-nik** [comment]
Спасибо, изображения загружены.
