### ISSUE TITLE
[BUG] FPS

### ISSUE THREAD

**Issue by waw555** [et-nik/gameap-legacy#14]
Устанавливая в настройках игры FPS, при создании сервера FPS стоит по умолчанию

Проверялось на CS 1.6

**Comment by et-nik** [comment]
В панели нет такого бага. Проверьте конфигурацию игрового сервера и параметры запуска.

Настройка FPS меняет значение параметра запуска sys_ticrate, возможно он отсутствует, либо его значение вновь меняется где-то в конфигурации сервера.
