### ISSUE TITLE
[Баг] Лимиты в опциях запуска сервера

### ISSUE THREAD

**Issue by DrCheater** [et-nik/gameap-legacy#16]
В общем, я пересказываю то, что не однократно обсуждалось на форуме ( http://forum.hldm.org/viewtopic.php?p=9672#p9672 ). Для корректной работы панели в настройках надо убрать -s {net_limit} -f {cpu_limit} -m {ram_limit}, т.к. при запуске server.sh переменные не заменяются на необходимые параметры. Я думаю, что надо это исправить.

**Comment by et-nik** [comment]
Замена хештегов {net_limit}, {cpu_limit}  {ram_limit} была исправлена в этом коммите - https://github.com/ET-NiK/GameAP/commit/9c8b76a1654f9bf759826a598fba7890fdd62656?diff=unified
