### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by mambochambo** [et-nik/gameap-legacy#19]
i have the following error message: http://prntscr.com/b1np2s
the log entry says:
ERROR - 2016-05-08 14:29:20 --> Severity: Warning  --> require_once(/var/www/vhosts/localhost.localdomain/httpdocs/upload/system/database/drivers/PDO/PDO_driver.php): failed to open stream: No such file or directory /var/www/vhosts/localhost.localdomain/httpdocs/upload/system/database/DB.php 140

Can you please help me out.
Thanks in advance.

**Comment by et-nik** [comment]
Try to mysqli 
or try to rename system/database/drivers/pdo/ to system/database/drivers/PDO/,
system/database/drivers/pdo/pdo_driver.php to PDO_driver.php
system/database/drivers/pdo/pdo_forge.php to PDO_forge.php
system/database/drivers/pdo/pdo_result.php to PDO_result.php
system/database/drivers/pdo/pdo_utility.php to PDO_utility.php

P.S. PDO drivers not tested. GameAP use CodeIgniter framework 2.1.3, in this framework version PDO drivers works incorrectly.

**Comment by mambochambo** [comment]
it worked, renamed it and set it to mysqli.
but now im getting this errror:Thats my log:
Database Driver Class Initialized
DEBUG - 2016-05-08 19:52:07 --> DB Transaction Failure
ERROR - 2016-05-08 19:52:07 --> Query error: Table 'gameap_.gameap_modules' doesn't exist
DEBUG - 2016-05-08 19:52:07 --> Language file loaded: language/russian/db_lang.php

**Comment by et-nik** [comment]
Delete application/config/database.php, application/config/gameap.php
Go to you-site.ru/install and set parameters.

How webserver you use?

**Comment by mambochambo** [comment]
Hi, thx for the reply. Im using linux ubuntu 14.04 webserver-
i did what u described, but now it says: database configuration file does not exist.
sorry for bothering so much 
Edit: its working now, i called the site with ?install behind the index.php, and now it working fine
Thx!
