### ISSUE TITLE
Проблема со скриптом установки

### ISSUE THREAD

**Issue by serfreeman1337** [et-nik/gameap-legacy#2]
Скрипт установки создает файл с данными для подключения до того как в БД были записаны таблицы панели.

В случае возникновении проблем с соединением с БД, установить панель через скрипт уже не получится, т.к. скрипт думает что панель уже установлена и редиректит на страницу авторизации.

Необходимо вручную удалять файл database.php что-бы перезапустить скрипт установки.

**Comment by et-nik** [comment]
Ошибка исправлена
