### ISSUE TITLE
404 на rcon_changer

### ISSUE THREAD

**Issue by SovRedBit** [et-nik/gameap-legacy#22]
При попытке смены rcon пароля из панели управления 1м сервером, он редиректит на 404.
Я покопался и нашёл в этом файле:
`grep -r "rcon_changer" /var/www/gameap/
/var/www/gameap/application/views/default/server_control/default.html:                  <div class="menu_icons"><a href="{site_url}rcon_changer/change/{server_id}"><img src="{base_url}themes/{template}/{style}/images/icons/field.png" /><br />Сменить RCON пароль</a></div>`
Что он направляет в никуда.

**Comment by et-nik** [comment]
Установите модуль RCON Changer - https://git.hldm.org/nik/gameap-rcon-changer

**Comment by SovRedBit** [comment]
Благодарю за совет, но к сожалению мой сервер был взломан, сейчас пытаюсь вернуть доступ, в скором времени попробую. P.S я вам написал в скайп, по одному вопросу.
