### ISSUE TITLE
Проблема с распаковкой архивов локального репозитория на Windows

### ISSUE THREAD

**Issue by serfreeman1337** [et-nik/gameap-legacy#3]
В процессе установки локального сервера создается будущая папка сервера и копируется архив с самим сервером из репозитория, но содержимое архива не извлекается. 

Проблема в том, что панель проверят наличие файла распаковщика 7z, но не умеет работать с алиасами ОС и считает путь не действительным.

Проблемный файл: **application\libraries\Control\drivers\Control_local.php**.
Функция **check_file**. Необходимо исправить проверку файла по алиасу пути в ОС Windows.

Возможный фикс:

```
if(strpos($file,"%PROGRAMFILES%") !== FALSE)
            return true;
```

**Comment by et-nik** [comment]
Проблема исправлена
https://github.com/ET-NiK/GameAP/commit/1bb78dfe9e4a1118e55a433976b52a87dcd69722
