### ISSUE TITLE
Ошибка определения статуса сервера

### ISSUE THREAD

**Issue by mymarche** [et-nik/gameap-legacy#4]
Проверял на сервере CS:S.
ошибка заключается в том что проверяется первая строка из запроса netstat не всегда нужного формата.
Мое решение:

<code>
function server_status()
{
    global $program, $dir, $ip, $port,  $start_command, $psexec;
    $pid=NULL;
    system("netstat -ano | findstr " . $port .">" . $dir . '\pid.txt');
    $file = file($dir . '\pid.txt');  
    //  TCP    10.99.1.8:27015        0.0.0.0:0              LISTENING       3496
    //  UDP    10.99.1.8:27015        _:_                                    3496  
    foreach ($file as $str) {
        $str = str_replace(' ', '', $str);
        if(preg_match('/^UDP(\d_).(\d_).(\d_).(\d_):(\d_)\_:*(\d*)/xsi', $str, $text)) {
            $pid = $text['6'];
        } 
    }
    if ($pid!=NULL) {
    system("echo " . $pid .">" . $dir . '\pid.txt');
    } else {
    system("echo NOT FOUND>" . $dir . '\pid.txt');
    }
    return $pid;
}
</code>

PS Извиняюсь за форматирование кода. Не получается дружить с GitHub Issues,

**Comment by et-nik** [comment]
А как выглядит netstat для CSS сервера?

**Comment by mymarche** [comment]
Выглядит вот так:
http://pastebin.com/PAA4ct72

**Comment by et-nik** [comment]
Проблема решена
https://github.com/ET-NiK/GameAP/commit/eaa437e2a7fce727db66af1878b3e2c3e00baa97
