### ISSUE TITLE
Не видит лог сервера CS:S

### ISSUE THREAD

**Issue by mymarche** [et-nik/gameap-legacy#5]
Проблема заключается в том что сервер SRCDS создает файл лога консоли по адресу SRCDS/{game}/console.log, в отличии от HLDS (HLDS/qconlose.log).
{game} в моем случае cstrike. 

Быстрое и универсальное решение не приходит в голову, только из за того что в файл server.exe не передается {game}.

**Comment by et-nik** [comment]
Да, известная проблема.
Как вариант, можно искать qconsole.log, а если отсутствует то console.log

**Comment by mymarche** [comment]
В обновлении 0.9.1 увидел намек на исправление данного недочета. 
Так вот. Оно работать не будет. ибо файл "console.log" лежит в подпапке "cstrike". 
Я в предыдущем сообщении писал об этом.

**Comment by et-nik** [comment]
Спасибо, исправлено
https://github.com/ET-NiK/GameAP/commit/f031a15814e2760db8f934344c6d6b2dd66e6386
